### ISSUE TITLE
Setup Laravel Pint for kawax/hatebu-delete

### ISSUE THREAD

**Issue by kawax** [kawax/hatebu-delete#1386]
## Goal
Setup Laravel Pint for automated code style checking and fixing in the `kawax/hatebu-delete` repository.

### Step 1: Investigate Repository and Install Dependencies
1. Check for the existence of a `composer.json` file in the repository.
2. If `composer.json` does not exist, terminate this process.
3. If `composer.json` exists, run the command:
   ```bash
   composer install
   ```

### Step 2: Ensure Laravel Pint is Installed
1. Check if `laravel/pint` is listed as a dependency in `composer.json`.
2. If not, install it using the command:
   ```bash
   composer require laravel/pint --dev
   ```

### Step 3: Create `pint.json` Configuration File
1. Check if `pint.json` exists at the root of the repository.
2. If it does not exist, create `pint.json` with the following content:
   ```json
   {
       "preset": "laravel",
       "rules": {
           "no_unused_imports": false
       }
   }
   ```

### Step 4: Create GitHub Actions Workflow for Linting
1. Check if `.github/workflows/lint.yml` exists.
2. If it does not exist, create `.github/workflows/lint.yml` with the following content:
   ```yaml
   name: linter

   on:
     push:
       branches:
         - develop
         - main
     pull_request:
       branches:
         - develop
         - main

   permissions:
     contents: write

   jobs:
     quality:
       runs-on: ubuntu-latest
       environment: Testing
       steps:
         - uses: actions/checkout@v4

         - name: Setup PHP
           uses: shivammathur/setup-php@v2
           with:
             php-version: '8.4'  # Consider using a version compatible with the project

         - name: Install Dependencies
           run: |
             composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

         - name: Run Lint
           run: vendor/bin/pint --test

         # - name: Commit Changes
         #   uses: stefanzweifel/git-auto-commit-action@v5
         #   with:
         #     commit_message: fix code style
         #     commit_options: '--no-verify'
         #     file_pattern: |
         #       **/*
         #       !.github/workflows/*
   ```

### Step 5: Run Pint and Fix Issues
1. Execute the command:
   ```bash
   vendor/bin/pint --test
   ```
2. If there are any errors, run the following command to fix them:
   ```bash
   vendor/bin/pint
   ```

### Step 6: Commit Changes and Create Pull Request
1. Commit all the changes made up to this point.
2. Create a new Pull Request with these changes.
